### ISSUE TITLE
Crash on trying to rendezvous

### ISSUE THREAD

**Issue by m9731526** [qfeys/ThrottleControlledAvionics#23]
This happens when I was moving into gravity zone of the Mon (but not yet captured), and trying to click the rendezvous button (out of curiosity...) to see if TCA can autoly get the craft into Mon Orbit then execute the rendezvous.

> [LOG 12:07:08.483] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.488] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.493] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.499] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.504] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.509] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.514] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.520] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.525] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.530] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()
> [LOG 12:07:08.536] getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
>    at System.Environment.get_StackTrace()
>    at Orbit.getObtAtUT(Double UT)
>    at Orbit.getRelativePositionAtUT(Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.SqrDistAtUT(.Orbit a, .Orbit b, Double UT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.NearestApproach(.Orbit a, .Orbit t, Double StartUT, Double StopUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.TrajectoryCalculator.ClosestApproach(.Orbit a, .Orbit t, Double StartUT, Double ByRef ApproachUT)
>    at ThrottleControlledAvionics.RendezvousTrajectory.update()
>    at ThrottleControlledAvionics.RendezvousTrajectory..ctor(ThrottleControlledAvionics.VesselWrapper vsl, Vector3d dV, Double startUT, ThrottleControlledAvionics.WayPoint target, Double min_PeR, Double transfer_time)
>    at ThrottleControlledAvionics.RendezvousAutopilot.get_CurrentTrajectory()
>    at ThrottleControlledAvionics.TrajectoryCalculator`1.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.update_trajectory()
>    at ThrottleControlledAvionics.RendezvousAutopilot.Update()
>    at ThrottleControlledAvionics.TCAModule.OnFixedUpdate()
>    at ThrottleControlledAvionics.ModuleTCA.<FixedUpdate>m__D(ThrottleControlledAvionics.TCAModule m)
>    at System.Collections.Generic.List`1[[ThrottleControlledAvionics.TCAModule, ThrottleControlledAvionics, Version=3.2.4.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1 action)
>    at ThrottleControlledAvionics.ModuleTCA.FixedUpdate()

**Comment by allista** [comment]
Thanks. I'll look into it.
By design TCA should not allow rendezvous with vessels not in the same SoE, so this should not have worked anyway. Just without the crash :)
